### ISSUE TITLE
Support for Node environment

### ISSUE THREAD

**Issue by pandzicivan** [phrase/i18next-phrase-backend#30]
ATM lib is not working in Node environment since it relies on [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) in order to generate the UUID.

When I execute the code:

```
i18n
  .use(I18nextPhraseBackend)
  .init({
    fallbackLng: 'en',
    backend: {
      distribution: 'DISTRIBUTION_ID',
      secret: 'YOUR_ENVIRONMENT_SECRET',
      appVersion: '1.0.0',
      cacheExpirationTime: 60 * 5, // time in seconds
    }
  });
```

There is error:

```
ReferenceError: crypto is not defined
    at Phrase.getUUID 
    at new Phrase
    at I18nextPhraseBackend.init
```

By looking in the https://github.com/phrase/i18next-phrase-backend/blob/main/src/phrase.ts#L102 I notice that lib relies on Web Crypto API.

My question is: Is support for Node env planned and was this lib intended usage browser only? Thanks in advance

**Comment by jablan** [comment]
Ćao Ivane,

I will open an internal ticket to ensure support for node env. It should be supported too.

**Comment by pandzicivan** [comment]
Pozdrav Mladene 😄 

I created a PR with updated tests for this issue in https://github.com/phrase/i18next-phrase-backend/pull/31. I am not sure if this is going to be acceptable solution for You since I added 3rd party dependancy to project(bundle diff is cca 100 bytes). If it is not acceptable I am going to use it this way until You rollout fix for this issue 👋🏻

**Comment by jablan** [comment]
Hey @pandzicivan I just released the version with your patch, thanks a lot for contributing!

As this project is rather new, we are quite curious how the people plan to use it, in order to better plan the further work on it and/or other related products. Would you be up to describe how do you plan to use it? Are you already using other Phrase products? Is your project commercial? etc. If you want, feel free to tell us more by writing to team-string-integrations@phrase.com
